export const services = [
  {
    id: 1,
    service: 'Консультация врача',
    price: '500',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 2,
    service: '',
    price: '',
    title: 'Профилактика и гигиена',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 3,
    service: 'Снятие зубных отложений (2 челюсти)',
    price: '4200',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 4,
    service: 'Гигиеническая чистка Air flow (2 челюсти)',
    price: '5000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 5,
    service: 'Инвазивная герметизация фиссур (1 зуб)',
    price: '2000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 6,
    service: '',
    price: '',
    title: 'Терапевтическая стоматология',
    smallTitle: '',
    subTitle:
      'Цены указаны с учетом всех необходимых сопутствующих манипуляций: анестезия, постановка пломбы, обработка, и пломбировка каналов, снимки и др.',
  },
  {
    id: 7,
    service: 'Лечение поверхностного кариеса',
    price: 'от 5 тыс.',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 8,
    service: 'Лечение среднего кариеса',
    price: 'от 6 тыс.',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 9,
    service: 'Лечение глубокого кариеса',
    price: 'от 7 тыс.',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 10,
    service: 'Лечение пульпита одноканального зуба',
    price: 'от 5 тыс.',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 11,
    service: 'Лечение пульпита двухканального зуба',
    price: 'от 8 тыс.',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 12,
    service: 'Лечение пульпита трехканального зуба',
    price: 'от 9 тыс.',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 13,
    service: 'Лечение периодонтита 1 канал',
    price: 'от 6 тыс.',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 14,
    service: '',
    price: '',
    title: 'Хирургическая стоматология',
    smallTitle: '',
    subTitle:
      'Цены указаны с учетом всех сопутствующих манипуляций: анестезия, наложение и снятие швов и др.',
  },
  {
    id: 15,
    service: 'Удаление зуба простое',
    price: '2300',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 16,
    service: 'Удаление зуба сложное',
    price: 'от 6000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 17,
    service: 'Удаление зуба сложное (ретинированный зуб)',
    price: 'от 8000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 18,
    service: 'Резекция верхушки корня',
    price: '12000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 19,
    service: '',
    price: '',
    title: '',
    smallTitle: 'Имплантация зубов',
    subTitle:
      'Цены указаны с учетом имплантата, анестезии, наложения и снятия швов и др. Без учета установки формирователя и ортопедической части работ',
  },
  {
    id: 20,
    service: 'Установка имплантата Mirell (Израиль)',
    price: '24000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 21,
    service: 'Установка имплантата Bio Horizont (США)',
    price: '41000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 22,
    service: 'Установка имплантата Impro (Германия), Yes (Ю.Корея)',
    price: '27000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 23,
    service: 'Установка имплантата Nobel Biocare (Швейцария)',
    price: '82000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 24,
    service: 'Установка формирователя',
    price: '4000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 25,
    service: '',
    price: '',
    title: '',
    smallTitle: 'Дополнительные услуги по имплантации (в случае необходимости)',
    subTitle: '',
  },
  {
    id: 26,
    service: 'Синуслифтинг закрытый (без стоимости расходных материалов)',
    price: '10000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 27,
    service: 'Синуслифтинг открытый (без стоимости расходных материалов)',
    price: '15000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 28,
    service: '',
    price: '',
    title: 'Ортопедия',
    smallTitle: '',
    subTitle: 'Цены указаны без учета слепков',
  },
  {
    id: 29,
    service: 'Металлокерамическая коронка',
    price: '9000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 30,
    service: 'Цельнолитая коронка',
    price: '8000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 31,
    service: 'Металлокерамическая коронка с опорой на имплантант',
    price: '17400',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 32,
    service: 'Абатмент',
    price: 'от 6200',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 33,
    service: 'Бюгельный протез простой',
    price: '37000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 34,
    service: 'Полный съемный протез (1 челюсть)',
    price: '22000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 35,
    service: 'Частичный съемный протез (1 челюсть)',
    price: '20000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 36,
    service: 'Винир керамический',
    price: '30000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 37,
    service: 'Слепок альгинатной массой',
    price: '800',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 38,
    service: 'Слепок силиконовой массой',
    price: '1500',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 39,
    service: '',
    price: '',
    title: 'Ортодонтия',
    smallTitle: '',
    subTitle:
      'Цены указаны с учетом аппаратуры (брекеты, дуги, лигатуры и др.), работы врача, наблюдение в течение лечения. Здесь представлены наиболее популярные брекет-системы и их комбинации. В клинике имеется широкий спектр брекет-систем',
  },
  {
    id: 40,
    service: '',
    price: '',
    title: '',
    smallTitle: 'Брекеты, брекет-системы (для 2-х зубных рядов)',
    subTitle: '',
  },
  {
    id: 41,
    service: 'Металлические брекеты H4 США',
    price: '200000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 42,
    service: 'Керамические брекеты Quic Klear',
    price: '260000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 43,
    service: 'Сапфировые брекеты',
    price: '236700',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 44,
    service: 'Лингвальная техника «Инкогнито»',
    price: '458600',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 45,
    service: 'Несъемный ретейнер 1 зубной ряд',
    price: '9000',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
  {
    id: 46,
    service: 'Каппа',
    price: '8900',
    title: '',
    smallTitle: '',
    subTitle: '',
  },
];
